---
title: "1. Basic"
output:
  html_document: 
    toc: yes
    theme: lumen
    highlight: tango
    # highlight: highlight\atom-one-dark.theme
    df_print: paged
---

# Setting up

<!-- install packages -->

```{r install-packages, echo=FALSE}

# These are the packages you already have

packages_you_have <- installed.packages()[, "Package"]

# These are all the packages we'll use in this document

packages_we_use <- c("rmarkdown", "dplyr", "leaflet", "conflicted")

# These are the packages you need to install

packages_you_need <- packages_we_use[!packages_we_use %in% packages_you_have]

# This will install the packages you don't already have

if (length(packages_you_need)) {
    
    cat("Installing:", paste(packages_you_need, collapse = ", "))
    
    install.packages(packages_you_need)
}

```

## Load packages

```{r load-packages, echo=TRUE, message=FALSE, warning=FALSE}

library(dplyr)
library(tidyr)
library(leaflet)
library(conflicted)

conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")

```

# Very simple

This is all you need to create a leaflet map:

```{r useless-map}

useless_map <- leaflet() %>% addTiles()
useless_map

```

It's not very useful, but it's nice that it works out of the box. Let's set the initial view so we can see something:

```{r sheep-meadow}

sheep_meadow <- useless_map %>% setView(lng = -73.975, lat = 40.772, zoom = 15)
sheep_meadow

```

It still only has a tile layer. Let's add a marker with a popup.

```{r sheep-meadow-marker}

sheep_meadow_marker <- 
    sheep_meadow %>% 
    addMarkers(
        lng = -73.975, 
        lat = 40.772, 
        label = "This is the Sheep Meadow",
        popup = "It's a nice place to hang out"
    )

sheep_meadow_marker

```

You can find more simple examples in the [leaflet R package docs](https://rstudio.github.io/leaflet/articles/).
